spring:
  application:
    name: "healthHub"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  web:
    locale: en

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



auth:
  tokens:
    access-token:
      secret: ${ACCESS_TOKEN_SECRET}
      duration: 900000
    refresh-token:
      duration: 172800000

authorities:
  tokens:
    refresh-password-token:
      duration: 3600000

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

---

spring:
  config:
    activate:
      on-profile: "test"

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
