spring:
  application:
    name: "healthHub"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: "test"

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
