create table users (
    id int primary key generated by default as identity,
    email varchar(128) unique not null,
    password varchar(68) not null,
    first_name varchar(64) not null,
    last_name varchar(64) not null,
    gender smallint not null,
    birth_date date not null,
    registration_date date not null,
    last_time_online timestamp with time zone
);